/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioController;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class ViewCargaHoraria extends javax.swing.JFrame {

    /**
     * Creates new form ViewCargaHoraria
     */
    public ViewCargaHoraria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBeneficio = new javax.swing.JPanel();
        jLabelTituloCargaHoraria = new javax.swing.JLabel();
        jLabelSubtituloCargaHoraria = new javax.swing.JLabel();
        jLabelRetornar = new javax.swing.JLabel();
        jButtonGerenciarAlterar = new javax.swing.JButton();
        jLabelDiasTrabalho = new javax.swing.JLabel();
        jCheckBoxDomingo = new javax.swing.JCheckBox();
        jCheckBoxSegunda = new javax.swing.JCheckBox();
        jCheckBoxTerca = new javax.swing.JCheckBox();
        jCheckBoxQuarta = new javax.swing.JCheckBox();
        jCheckBoxQuinta = new javax.swing.JCheckBox();
        jCheckBoxSexta = new javax.swing.JCheckBox();
        jCheckBoxSabado = new javax.swing.JCheckBox();
        jLabelCargaHoraria = new javax.swing.JLabel();
        jTextFieldCargaHoraria = new javax.swing.JTextField();
        jLabelDiasFerias = new javax.swing.JLabel();
        jTextFieldDiasFerias = new javax.swing.JTextField();
        jLabelPretensao = new javax.swing.JLabel();
        jTextFieldPretensao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Free! - Alterar Carga Horária / Pretensão Salarial");
        setResizable(false);

        jPanelBeneficio.setBackground(new java.awt.Color(0, 0, 0));

        jLabelTituloCargaHoraria.setFont(new java.awt.Font("The Bold Font", 0, 30)); // NOI18N
        jLabelTituloCargaHoraria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloCargaHoraria.setText("<html>\nALTERAR CARGA HORÁRIA / PRETENSÃO<br>SALARIAL\n</html>");

        jLabelSubtituloCargaHoraria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubtituloCargaHoraria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubtituloCargaHoraria.setText("Você no controle.");

        jLabelRetornar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRetornar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRetornar.setText("Retornar >>");
        jLabelRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRetornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRetornarMouseClicked(evt);
            }
        });

        jButtonGerenciarAlterar.setBackground(new java.awt.Color(255, 0, 102));
        jButtonGerenciarAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerenciarAlterar.setText("Alterar");
        jButtonGerenciarAlterar.setToolTipText("");
        jButtonGerenciarAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGerenciarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarAlterarActionPerformed(evt);
            }
        });

        jLabelDiasTrabalho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDiasTrabalho.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiasTrabalho.setText("Dias de trabalho:");

        jCheckBoxDomingo.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxDomingo.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxDomingo.setText("D");

        jCheckBoxSegunda.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxSegunda.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxSegunda.setText("S");

        jCheckBoxTerca.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxTerca.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTerca.setText("T");

        jCheckBoxQuarta.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxQuarta.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxQuarta.setText("Q");

        jCheckBoxQuinta.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxQuinta.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxQuinta.setText("Q");

        jCheckBoxSexta.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxSexta.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxSexta.setText("S");

        jCheckBoxSabado.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxSabado.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxSabado.setText("S");

        jLabelCargaHoraria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCargaHoraria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCargaHoraria.setText("Carga horária diária:");

        jLabelDiasFerias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDiasFerias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiasFerias.setText("Dias de férias:");

        jLabelPretensao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPretensao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPretensao.setText("Pretensão salarial:");

        javax.swing.GroupLayout jPanelBeneficioLayout = new javax.swing.GroupLayout(jPanelBeneficio);
        jPanelBeneficio.setLayout(jPanelBeneficioLayout);
        jPanelBeneficioLayout.setHorizontalGroup(
            jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSubtituloCargaHoraria)
                    .addComponent(jLabelTituloCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDiasTrabalho)
                    .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jCheckBoxDomingo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSegunda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxTerca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxQuarta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxQuinta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSexta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSabado))
                    .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButtonGerenciarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)
                            .addComponent(jLabelRetornar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBeneficioLayout.createSequentialGroup()
                            .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCargaHoraria)
                                .addComponent(jTextFieldCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDiasFerias)
                                .addComponent(jTextFieldDiasFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPretensao)
                                .addComponent(jTextFieldPretensao, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelBeneficioLayout.setVerticalGroup(
            jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTituloCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSubtituloCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                        .addComponent(jLabelDiasFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDiasFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                        .addComponent(jLabelDiasTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxDomingo)
                            .addComponent(jCheckBoxSegunda)
                            .addComponent(jCheckBoxTerca)
                            .addComponent(jCheckBoxQuarta)
                            .addComponent(jCheckBoxQuinta)
                            .addComponent(jCheckBoxSexta)
                            .addComponent(jCheckBoxSabado))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                        .addComponent(jLabelPretensao, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPretensao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGerenciarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBeneficio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBeneficio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerenciarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarAlterarActionPerformed
        // TODO add your handling code here:
        ArrayList<String> dias_trabalhados = new ArrayList<String>();
        if(jCheckBoxDomingo.isSelected())
            dias_trabalhados.add("Domingo");
        if(jCheckBoxSegunda.isSelected())
            dias_trabalhados.add("Segunda");
        if(jCheckBoxTerca.isSelected())
            dias_trabalhados.add("Terça");
        if(jCheckBoxQuarta.isSelected())
            dias_trabalhados.add("Quarta");
        if(jCheckBoxQuinta.isSelected())
            dias_trabalhados.add("Quinta");
        if(jCheckBoxSexta.isSelected())
            dias_trabalhados.add("Sexta");
        if(jCheckBoxSabado.isSelected())
            dias_trabalhados.add("Sábado");
        int carga_horaria_diaria = Integer.parseInt(jTextFieldCargaHoraria.getText());
        int dias_ferias = Integer.parseInt(jTextFieldDiasFerias.getText());
        float pretensao_salarial = Float.parseFloat(jTextFieldPretensao.getText());
        boolean sucesso;
        
        try
        {
            UsuarioController usuarioController = new UsuarioController();
            sucesso = usuarioController.atualizarUsuario(dias_trabalhados, carga_horaria_diaria, dias_ferias, pretensao_salarial);
            if(sucesso == true)
            {
                JOptionPane.showMessageDialog(null, "Atualização realizada com sucesso!");
                //this.limparTelaCadastroUsuario(evt);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Campos não preenchidos corretamente!");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonGerenciarAlterarActionPerformed

    private void jLabelRetornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRetornarMouseClicked
        // TODO add your handling code here:
        ViewPrincipal viewPrincipal = new ViewPrincipal();
        viewPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelRetornarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCargaHoraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCargaHoraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCargaHoraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCargaHoraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCargaHoraria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerenciarAlterar;
    private javax.swing.JCheckBox jCheckBoxDomingo;
    private javax.swing.JCheckBox jCheckBoxQuarta;
    private javax.swing.JCheckBox jCheckBoxQuinta;
    private javax.swing.JCheckBox jCheckBoxSabado;
    private javax.swing.JCheckBox jCheckBoxSegunda;
    private javax.swing.JCheckBox jCheckBoxSexta;
    private javax.swing.JCheckBox jCheckBoxTerca;
    private javax.swing.JLabel jLabelCargaHoraria;
    private javax.swing.JLabel jLabelDiasFerias;
    private javax.swing.JLabel jLabelDiasTrabalho;
    private javax.swing.JLabel jLabelPretensao;
    private javax.swing.JLabel jLabelRetornar;
    private javax.swing.JLabel jLabelSubtituloCargaHoraria;
    private javax.swing.JLabel jLabelTituloCargaHoraria;
    private javax.swing.JPanel jPanelBeneficio;
    private javax.swing.JTextField jTextFieldCargaHoraria;
    private javax.swing.JTextField jTextFieldDiasFerias;
    private javax.swing.JTextField jTextFieldPretensao;
    // End of variables declaration//GEN-END:variables
}
