/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BeneficioController;
import controller.CustoController;
import controller.UsuarioController;
import dao.ExceptionDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Beneficio;
import model.Custo;

/**
 *
 * @author Gabriel
 */
public class ViewBeneficio extends javax.swing.JFrame {

    /**
     * Creates new form ViewBeneficio
     */
    public ViewBeneficio() {
        initComponents();
        gerenciaBotoes(0);
        refreshTable();
    }
    
    private void preencheCampos(String identificacao, float valor, String periodicidade)
    {
        jTextFieldIdentificacao.setText(identificacao);
        jTextFieldValor.setText(String.valueOf(valor));
        jComboBoxPeriodicidade.setSelectedItem(periodicidade);
    }
    
    private void refreshTable()
    {
        DefaultTableModel tableModel = (DefaultTableModel) jTableBeneficio.getModel();
        tableModel.setRowCount(0);
        BeneficioController beneficioController = new BeneficioController();
        try
        {
            
            ArrayList<Beneficio> beneficios = beneficioController.listarBeneficios();
            beneficios.forEach((Beneficio beneficio) -> {
                String periodicidade = "";
                if(beneficio.getPeriodicidade() == 'd')
                    periodicidade = "Diário";
                if(beneficio.getPeriodicidade() == 's')
                    periodicidade = "Semanal";
                if(beneficio.getPeriodicidade() == 'm')
                    periodicidade = "Mensal";
                if(beneficio.getPeriodicidade() == 'a')
                    periodicidade = "Anual";
                tableModel.addRow(new Object[] {beneficio.getCodigo(),
                                                beneficio.getIdentificacao(),
                                                periodicidade,
                                                beneficio.getValor()
                });
            });
            jTableBeneficio.setModel(tableModel);
        }
        catch(ExceptionDAO e)
        {
            e.printStackTrace();
        }
    }

     private void limparTelaBeneficio()
    {
        jTextFieldIdentificacao.setText("");
        jTextFieldValor.setText("");
        jComboBoxPeriodicidade.setSelectedItem("Diário");
        gerenciaBotoes(0);
    }
    
    private void gerenciaBotoes(int cod)
    {
        if(cod == 0)
        {
            jButtonCadastrar.setEnabled(true);
            jButtonGerenciarAlterar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
        }
        else
        {
            jButtonCadastrar.setEnabled(false);
            jButtonGerenciarAlterar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
        }
    } 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBeneficio = new javax.swing.JPanel();
        jLabelTituloBeneficio = new javax.swing.JLabel();
        jLabelSubtituloBeneficio = new javax.swing.JLabel();
        jLabelRetornar = new javax.swing.JLabel();
        jTextFieldIdentificacao = new javax.swing.JTextField();
        jLabelIdentificacao = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jComboBoxPeriodicidade = new javax.swing.JComboBox<>();
        jLabelPeriodicidade = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonGerenciarAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBeneficio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Free! - Gerenciar Benefícios");
        setResizable(false);

        jPanelBeneficio.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBeneficio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBeneficioMouseClicked(evt);
            }
        });

        jLabelTituloBeneficio.setFont(new java.awt.Font("The Bold Font", 0, 30)); // NOI18N
        jLabelTituloBeneficio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloBeneficio.setText("Gerenciar benefícios");

        jLabelSubtituloBeneficio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubtituloBeneficio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubtituloBeneficio.setText("Às vezes só precisamos de um descanso.");

        jLabelRetornar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRetornar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRetornar.setText("Retornar >>");
        jLabelRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRetornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRetornarMouseClicked(evt);
            }
        });

        jTextFieldIdentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificacaoActionPerformed(evt);
            }
        });

        jLabelIdentificacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIdentificacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdentificacao.setText("Identificação do benefício:");

        jLabelValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor:");

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });
        jTextFieldValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorKeyTyped(evt);
            }
        });

        jComboBoxPeriodicidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diário", "Semanal", "Mensal", "Anual" }));

        jLabelPeriodicidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPeriodicidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPeriodicidade.setText("Periodicidade");

        jButtonCadastrar.setBackground(new java.awt.Color(255, 0, 102));
        jButtonCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.setToolTipText("");
        jButtonCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonGerenciarAlterar.setBackground(new java.awt.Color(255, 0, 102));
        jButtonGerenciarAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerenciarAlterar.setText("Alterar");
        jButtonGerenciarAlterar.setToolTipText("");
        jButtonGerenciarAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGerenciarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(255, 0, 102));
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("");
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableBeneficio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Identificação", "Periodicidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBeneficio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBeneficioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBeneficio);

        javax.swing.GroupLayout jPanelBeneficioLayout = new javax.swing.GroupLayout(jPanelBeneficio);
        jPanelBeneficio.setLayout(jPanelBeneficioLayout);
        jPanelBeneficioLayout.setHorizontalGroup(
            jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                        .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIdentificacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPeriodicidade)
                            .addComponent(jComboBoxPeriodicidade, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                        .addComponent(jLabelSubtituloBeneficio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                        .addComponent(jLabelTituloBeneficio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelRetornar)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBeneficioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGerenciarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addComponent(jScrollPane1)
        );
        jPanelBeneficioLayout.setVerticalGroup(
            jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                        .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSubtituloBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTituloBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                                .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPeriodicidade, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPeriodicidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                                .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))
                    .addGroup(jPanelBeneficioLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBeneficioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGerenciarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBeneficio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBeneficio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificacaoActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        String identificacao = jTextFieldIdentificacao.getText();
        float valor = Float.parseFloat(jTextFieldValor.getText());
        char periodicidade = 'd';
        if(jComboBoxPeriodicidade.getSelectedItem().toString() == "Diário")
            periodicidade = 'd';
        if(jComboBoxPeriodicidade.getSelectedItem().toString() == "Semanal")
            periodicidade = 's';
        if(jComboBoxPeriodicidade.getSelectedItem().toString() == "Mensal")
            periodicidade = 'm';
        if(jComboBoxPeriodicidade.getSelectedItem().toString() == "Anual")
            periodicidade = 'a';
        boolean sucesso;
        try
        {
            BeneficioController beneficioController = new BeneficioController();
            sucesso = beneficioController.cadastrarBeneficio(identificacao, valor, periodicidade);
            if(sucesso == true)
            {
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                refreshTable();
                this.limparTelaBeneficio();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Campos não preenchidos corretamente!");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonGerenciarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarAlterarActionPerformed
        // TODO add your handling code here:
        String identificacao = jTextFieldIdentificacao.getText();
        float valor = Float.parseFloat(jTextFieldValor.getText());
        int codigo = Integer.parseInt(String.valueOf(jTableBeneficio.getValueAt(jTableBeneficio.getSelectedRow(), 0)));
        char periodicidade = 'd';
        if(jComboBoxPeriodicidade.getSelectedItem().toString() == "Diário")
            periodicidade = 'd';
        if(jComboBoxPeriodicidade.getSelectedItem().toString() == "Semanal")
            periodicidade = 's';
        if(jComboBoxPeriodicidade.getSelectedItem().toString() == "Mensal")
            periodicidade = 'm';
        if(jComboBoxPeriodicidade.getSelectedItem().toString() == "Anual")
            periodicidade = 'a';
        boolean sucesso;
        try
        {
            BeneficioController beneficioController = new BeneficioController();
            UsuarioController usuarioController = new UsuarioController();
            sucesso = beneficioController.atualizarBeneficio(codigo, identificacao, valor, periodicidade);
            if(sucesso == true)
            {
                JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
                refreshTable();
                this.limparTelaBeneficio();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Campos não preenchidos corretamente!");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonGerenciarAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(String.valueOf(jTableBeneficio.getValueAt(jTableBeneficio.getSelectedRow(), 0)));
        boolean sucesso;
        try
        {
            BeneficioController beneficioController = new BeneficioController();
            UsuarioController usuarioController = new UsuarioController();
            sucesso = beneficioController.excluirBeneficio(codigo);
            if(sucesso == true)
            {
                JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!");
                refreshTable();
                this.limparTelaBeneficio();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro!");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(((c < '0') || (c > '9')) && (c != '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldValorKeyTyped

    private void jLabelRetornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRetornarMouseClicked
        // TODO add your handling code here:
        ViewPrincipal viewPrincipal = new ViewPrincipal();
        viewPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelRetornarMouseClicked

    private void jTableBeneficioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBeneficioMouseClicked
        // TODO add your handling code here:
        gerenciaBotoes(1);
        if(evt.getClickCount() == 1)
        {
            String identificacao = (String)jTableBeneficio.getModel().getValueAt(jTableBeneficio.getSelectedRow(), 1);
            String periodicidade = (String)jTableBeneficio.getModel().getValueAt(jTableBeneficio.getSelectedRow(), 2);
            Float valor = Float.parseFloat(String.valueOf(jTableBeneficio.getModel().getValueAt(jTableBeneficio.getSelectedRow(), 3)));
            preencheCampos(identificacao, valor, periodicidade);
        }
    }//GEN-LAST:event_jTableBeneficioMouseClicked

    private void jPanelBeneficioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBeneficioMouseClicked
        // TODO add your handling code here:
        jTableBeneficio.clearSelection();
        limparTelaBeneficio();
    }//GEN-LAST:event_jPanelBeneficioMouseClicked
                                   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBeneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBeneficio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGerenciarAlterar;
    private javax.swing.JComboBox<String> jComboBoxPeriodicidade;
    private javax.swing.JLabel jLabelIdentificacao;
    private javax.swing.JLabel jLabelPeriodicidade;
    private javax.swing.JLabel jLabelRetornar;
    private javax.swing.JLabel jLabelSubtituloBeneficio;
    private javax.swing.JLabel jLabelTituloBeneficio;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelBeneficio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBeneficio;
    private javax.swing.JTextField jTextFieldIdentificacao;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
