/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.EmailLogado;

/**
 *
 * @author Gabriel
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelTituloPrincipal = new javax.swing.JLabel();
        jLabelSubtituloPrincipal = new javax.swing.JLabel();
        jButtonGerenciarProjetos = new javax.swing.JButton();
        jButtonGerenciarBeneficios = new javax.swing.JButton();
        jButtonGerenciarCustos1 = new javax.swing.JButton();
        jButtonGerenciarCargaHoraria = new javax.swing.JButton();
        jLabelLogoff = new javax.swing.JLabel();
        jLabelLogadoComo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Free! - Sistema de Gestão para Freelancers");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        jLabelTituloPrincipal.setFont(new java.awt.Font("The Bold Font", 0, 30)); // NOI18N
        jLabelTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloPrincipal.setText("oLÁ!");

        jLabelSubtituloPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSubtituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubtituloPrincipal.setText("Selecione uma funcionalidade.");

        jButtonGerenciarProjetos.setBackground(new java.awt.Color(255, 0, 102));
        jButtonGerenciarProjetos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerenciarProjetos.setText("Gerenciar Projetos");
        jButtonGerenciarProjetos.setToolTipText("");
        jButtonGerenciarProjetos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGerenciarProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarProjetosActionPerformed(evt);
            }
        });

        jButtonGerenciarBeneficios.setBackground(new java.awt.Color(255, 0, 102));
        jButtonGerenciarBeneficios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerenciarBeneficios.setText("<html>\nGerenciar<br>Beneficios\n</html>");
        jButtonGerenciarBeneficios.setToolTipText("");
        jButtonGerenciarBeneficios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGerenciarBeneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarBeneficiosActionPerformed(evt);
            }
        });

        jButtonGerenciarCustos1.setBackground(new java.awt.Color(255, 0, 102));
        jButtonGerenciarCustos1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerenciarCustos1.setText("Gerenciar Custos");
        jButtonGerenciarCustos1.setToolTipText("");
        jButtonGerenciarCustos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGerenciarCustos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarCustos1ActionPerformed(evt);
            }
        });

        jButtonGerenciarCargaHoraria.setBackground(new java.awt.Color(255, 0, 102));
        jButtonGerenciarCargaHoraria.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerenciarCargaHoraria.setText("<html>\nGerenciar Carga <br> Horaria e Salarios\n</html>");
        jButtonGerenciarCargaHoraria.setToolTipText("");
        jButtonGerenciarCargaHoraria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGerenciarCargaHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarCargaHorariaActionPerformed(evt);
            }
        });

        jLabelLogoff.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelLogoff.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogoff.setText("Fazer logoff");
        jLabelLogoff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogoff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoffMouseClicked(evt);
            }
        });

        jLabelLogadoComo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelLogadoComo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogadoComo.setText("Logado como:");
        jLabelLogadoComo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogoff)
                    .addComponent(jLabelSubtituloPrincipal)
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                            .addComponent(jLabelTituloPrincipal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLogadoComo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPrincipalLayout.createSequentialGroup()
                            .addComponent(jButtonGerenciarProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonGerenciarCustos1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonGerenciarBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonGerenciarCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogadoComo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSubtituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonGerenciarProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonGerenciarCustos1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonGerenciarCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonGerenciarBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerenciarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarProjetosActionPerformed
        // TODO add your handling code here:
        ViewProjeto viewProjeto = new ViewProjeto();
        viewProjeto.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGerenciarProjetosActionPerformed

    private void jButtonGerenciarBeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarBeneficiosActionPerformed
        // TODO add your handling code here:
        ViewBeneficio viewBeneficio = new ViewBeneficio();
        viewBeneficio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGerenciarBeneficiosActionPerformed

    private void jButtonGerenciarCustos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarCustos1ActionPerformed
        // TODO add your handling code here:
        ViewCusto viewCusto = new ViewCusto();
        viewCusto.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGerenciarCustos1ActionPerformed

    private void jButtonGerenciarCargaHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarCargaHorariaActionPerformed
        // TODO add your handling code here:
        ViewCargaHoraria viewCargaHoraria = new ViewCargaHoraria();
        viewCargaHoraria.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGerenciarCargaHorariaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabelLogadoComo.setText("Logado como: " + EmailLogado.getInstance().getEmail());
    }//GEN-LAST:event_formWindowOpened

    private void jLabelLogoffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoffMouseClicked
        // TODO add your handling code here:
        ViewLogin viewLogin = new ViewLogin();
        viewLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelLogoffMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerenciarBeneficios;
    private javax.swing.JButton jButtonGerenciarCargaHoraria;
    private javax.swing.JButton jButtonGerenciarCustos1;
    private javax.swing.JButton jButtonGerenciarProjetos;
    private javax.swing.JLabel jLabelLogadoComo;
    private javax.swing.JLabel jLabelLogoff;
    private javax.swing.JLabel jLabelSubtituloPrincipal;
    private javax.swing.JLabel jLabelTituloPrincipal;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
